services:
  workerman-server.command.http:
    class: WorkermanServerBundle\Command\WorkermanHttpCommand
    autowire: true
    tags: [ 'console.command' ]
  workerman-server.command.ws:
    class: WorkermanServerBundle\Command\WorkermanWsCommand
    autowire: true
    tags: [ 'console.command' ]
